name: Data Schema Code Convention
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  SQLLinter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install SQLFluff
        run: pip install sqlfluff
      - name: Lint SQL schema
        run: sqlfluff lint DataSchemaModified.sql --dialect postgres

  JSONLinter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install JSONLint
        run: npm install -g @prantlf/jsonlint
      - name: Lint JSON schema
        run: jsonlint DataSchema.json
