name: PrintProcessingSoftwareVersions
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  PrintProcessingSoftwareVersions:
    runs-on: ubuntu-latest
    steps:
      - name: Print Node.js Version
        run: node --version
      - name: Print Python Version
        run: python3 --version
      - name: Print npm Version
        run: npm --version
  PrintDBMSVersions:
    runs-on: ubuntu-latest
    needs: [PrintProcessingSoftwareVersions]
    steps:
      - name: Print PostgreSQL Version
        run: psql --version
      - name: Print MongoDB Version
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wget gpg
          wget -qO - https://www.mongodb.org/static/pgp/server-8.0.asc | sudo gpg --dearmor -o /usr/share/keyrings/mongodb-8.gpg
          echo "deb [ signed-by=/usr/share/keyrings/mongodb-8.gpg ] https://repo.mongodb.org/apt/ubuntu noble/mongodb-org/8.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-8.0.list
          sudo apt-get update -y
          sudo apt-get install -y mongodb-org-server
          mongod --version
